name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libx11-dev \
            libasound2-dev \
            libudev-dev \
            libxkbcommon-x11-0 \
            xvfb \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libxcursor1 \
            libxi6 \
            libxrandr2

      - name: Run tests
        run: xvfb-run -a cargo test

      - name: Build for Linux
        run: xvfb-run -a cargo build --release

      - name: Build WASM for web
        run: |
          trunk build --release

      - name: Create release directory
        run: |
          mkdir -p release
          cp target/release/bevy-tic-tac-toe release/
          cp README.md release/
          cp -r dist release/web || echo "No WASM build"
          cp -r assets release/ || echo "No assets directory"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./release

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
