name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: bevy-tic-tac-toe-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: bevy-tic-tac-toe-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            name: bevy-tic-tac-toe-macos-x86_64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libx11-dev \
            libasound2-dev \
            libudev-dev \
            libxkbcommon-x11-0 \
            xvfb \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libxcursor1 \
            libxi6 \
            libxrandr2

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a cargo test

      - name: Run tests (Non-Linux)
        if: runner.os != 'Linux'
        run: cargo test

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a cargo build --release --target ${{ matrix.target }}

      - name: Build (Non-Linux)
        if: runner.os != 'Linux'
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        shell: bash
        run: |
          binary_name="bevy-tic-tac-toe"
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            binary_name="bevy-tic-tac-toe.exe"
          fi

          cd target/${{ matrix.target }}/release
          tar czf ../../../${{ matrix.name }}.tar.gz $binary_name
          cd -

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.name }}.tar.gz
